theme = 'ananke'
baseURL = "https://tercioofparma.github.io/"

[languages]
	[languages.en]
		title = "Elliot Lake"
		weight = 1
		contentDir = "content"
		
[caches]
  [caches.images]
    dir = ':cacheDir/images'
