theme = 'ananke'
baseURL = "elliotlake.xyz"
relativeURLs = true

[languages]
	[languages.en]
		title = "Elliot Lake"
		weight = 1
		contentDir = "content"
		
[caches]
  [caches.images]
    dir = ':cacheDir/images'
    
  
